"""empty message

Revision ID: 06f37ca9533e
Revises: 811fa5326585
Create Date: 2025-07-16 05:14:42.307803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f37ca9533e'
down_revision = '811fa5326585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gaming_group', schema=None) as batch_op:
        batch_op.alter_column('creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('gaming_group_creator_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['creator_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gaming_group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('gaming_group_creator_id_fkey'), 'user', ['creator_id'], ['id'])
        batch_op.alter_column('creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
