"""empty message

Revision ID: 126caad4394a
Revises: f76dbe0bf4a7
Create Date: 2025-07-22 03:58:03.794724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126caad4394a'
down_revision = 'f76dbe0bf4a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('steam_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=17),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('steam_id',
               existing_type=sa.String(length=17),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
