"""empty message

Revision ID: 191f9ddb6a75
Revises: 790d2dea8791
Create Date: 2025-07-18 21:31:24.332036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191f9ddb6a75'
down_revision = '790d2dea8791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
