"""Increase User password_hash length to 256

Revision ID: 811fa5326585
Revises: 56f38dfa28bc
Create Date: 2025-07-12 21:07:38.668007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811fa5326585'
down_revision = '56f38dfa28bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # First rename password to password_hash if it exists
        batch_op.alter_column('password',
               new_column_name='password_hash',
               existing_type=sa.String(),
               existing_nullable=False)
        
        # Then alter the column type
        batch_op.alter_column('password_hash',
               existing_type=sa.String(),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # First revert the column type
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.String(),
               existing_nullable=False)
        
        # Then rename back to password
        batch_op.alter_column('password_hash',
               new_column_name='password',
               existing_type=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###
