"""empty message

Revision ID: a41fb3d5b5fe
Revises: 06f37ca9533e
Create Date: 2025-07-16 18:46:54.690160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41fb3d5b5fe'
down_revision = '06f37ca9533e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('game_session_group_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'gaming_group', ['group_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('game_session_group_id_fkey'), 'gaming_group', ['group_id'], ['id'])

    # ### end Alembic commands ###
