"""upgrade all other tables

Revision ID: eb4e6c498452
Revises: ca6625125163
Create Date: 2025-07-04 02:00:51.867127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
import datetime


# revision identifiers, used by Alembic.
revision = 'eb4e6c498452'
down_revision = 'ca6625125163'
branch_labels = None
depends_on = None




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False,
               existing_server_default=sa.text("'temp_user'::character varying"))
        batch_op.drop_column('gaming_style')
        batch_op.drop_column('favorite_genres')
        batch_op.drop_column('gaming_preferences')
        batch_op.drop_column('steam_library_synced_at')
        batch_op.drop_column('is_steam_connected')
        batch_op.drop_column('steam_profile_url')
        batch_op.drop_column('steam_avatar_url')
        batch_op.drop_column('steam_username')
        batch_op.drop_column('steam_id')
        batch_op.drop_column('last_login')
        batch_op.drop_column('created_at')
        batch_op.drop_column('bio')
        batch_op.drop_column('avatar_url')

    op.drop_table('group_members')
    op.drop_table('game_session')
    op.drop_table('game')
    op.drop_table('user_games')
    op.drop_table('steam_link')
    op.drop_table('gaming_group')
    op.drop_table('steam_game')
    # ### end Alembic commands ###
