"""upgrade all other tables

Revision ID: eb4e6c498452
Revises: ca6625125163
Create Date: 2025-07-04 02:00:51.867127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
import datetime


# revision identifiers, used by Alembic.
revision = 'eb4e6c498452'
down_revision = 'ca6625125163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steam_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steam_appid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('header_image', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('categories', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('supported_languages', sa.Text(), nullable=True),
    sa.Column('multiplayer', sa.Boolean(), nullable=False),
    sa.Column('co_op', sa.Boolean(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('min_players', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(length=20), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('steam_appid')
    )
    op.create_table('gaming_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('invite_code', sa.String(length=10), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('preferred_genres', sa.Text(), nullable=True),
    sa.Column('gaming_style', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_table('steam_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steamid', sa.String(length=20), nullable=False),
    sa.Column('persona', sa.String(length=120), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('steamid')
    )
    op.create_table('user_games',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('hours_played', sa.Integer(), nullable=True),
    sa.Column('last_played', sa.DateTime(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['steam_game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'game_id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('playtime', sa.Integer(), nullable=False),
    sa.Column('steam_link_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['steam_link_id'], ['steam_link.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('session_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('vote_results', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['steam_game.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['gaming_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['gaming_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('steam_id', sa.String(length=17), nullable=True))
        batch_op.add_column(sa.Column('steam_username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('steam_avatar_url', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('steam_profile_url', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('is_steam_connected', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('steam_library_synced_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('gaming_preferences', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('favorite_genres', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gaming_style', sa.String(length=50), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True,
               existing_server_default=sa.text("'temp_user'::character varying"))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['steam_id'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False,
               existing_server_default=sa.text("'temp_user'::character varying"))
        batch_op.drop_column('gaming_style')
        batch_op.drop_column('favorite_genres')
        batch_op.drop_column('gaming_preferences')
        batch_op.drop_column('steam_library_synced_at')
        batch_op.drop_column('is_steam_connected')
        batch_op.drop_column('steam_profile_url')
        batch_op.drop_column('steam_avatar_url')
        batch_op.drop_column('steam_username')
        batch_op.drop_column('steam_id')
        batch_op.drop_column('last_login')
        batch_op.drop_column('created_at')
        batch_op.drop_column('bio')
        batch_op.drop_column('avatar_url')

    op.drop_table('group_members')
    op.drop_table('game_session')
    op.drop_table('game')
    op.drop_table('user_games')
    op.drop_table('steam_link')
    op.drop_table('gaming_group')
    op.drop_table('steam_game')
    # ### end Alembic commands ###
