"""Add enhanced user authentication

Revision ID: ed560a3d9535
Revises: e2d690e1334a
Create Date: 2025-06-24 00:19:46.935155

"""
from alembic import op
from sqlalchemy import inspect
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ed560a3d9535'
down_revision = 'e2d690e1334a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    insp = inspect(conn)
    columns = [col['name'] for col in insp.get_columns('user')]

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_steam_connected', sa.Boolean(), nullable=False))
        if 'password_hash' in columns:
            batch_op.alter_column('password_hash',
                existing_type=sa.VARCHAR(length=256),
                type_=sa.String(length=200),
                existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.drop_column('is_steam_connected')
        batch_op.drop_column('is_active')
        batch_op.drop_column('last_login')
        batch_op.drop_column('bio')
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
