"""Add missing user columns

Revision ID: f76dbe0bf4a7
Revises: 191f9ddb6a75
Create Date: 2025-07-20 00:57:21.633889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76dbe0bf4a7'
down_revision = '191f9ddb6a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('steam_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('steam_username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('steam_avatar_url', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('steam_profile_url', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('steam_connected', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('steam_library_synced_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('gaming_preferences', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('favorite_genres', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gaming_style', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('total_games', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('total_votes_cast', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('favorite_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gaming_activity_level', sa.String(length=20), server_default='casual', nullable=False))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_user_steam_id', ['steam_id'])
        batch_op.create_foreign_key('fk_user_favorite_game', 'steam_game', ['favorite_game_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_favorite_game', type_='foreignkey')
        batch_op.drop_constraint('uq_user_steam_id', type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('gaming_activity_level')
        batch_op.drop_column('favorite_game_id')
        batch_op.drop_column('total_votes_cast')
        batch_op.drop_column('total_games')
        batch_op.drop_column('gaming_style')
        batch_op.drop_column('favorite_genres')
        batch_op.drop_column('gaming_preferences')
        batch_op.drop_column('steam_library_synced_at')
        batch_op.drop_column('steam_connected')
        batch_op.drop_column('steam_profile_url')
        batch_op.drop_column('steam_avatar_url')
        batch_op.drop_column('steam_username')
        batch_op.drop_column('steam_id')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###