"""add SteamLink & Game

Revision ID: fd370ea4c3a0
Revises: 0763d677d453
Create Date: 2025-07-02 22:40:50.464086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd370ea4c3a0'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steam_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steamid', sa.String(length=20), nullable=False),
    sa.Column('persona', sa.String(length=120), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('steamid')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('playtime', sa.Integer(), nullable=False),
    sa.Column('steam_link_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['steam_link_id'], ['steam_link.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_table('steam_link')
    # ### end Alembic commands ###
